version: '3.8'

services:
  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock  # Allow container to manage other containers
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
    networks:
      - browser-network

networks:
  browser-network:
    name: browser-network 