apiVersion: v1
kind: Service
metadata:
  name: browser-infra-service
  labels:
    app: browser-infra-service
spec:
  type: ClusterIP
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
    name: http
  selector:
    app: browser-infra-service 