apiVersion: v1
kind: Service
metadata:
  name: browser-instance
  labels:
    app: browser-instance
spec:
  type: ClusterIP
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
    name: http
  selector:
    app: browser-instance 