apiVersion: v1
kind: ConfigMap
metadata:
  name: browser-infra-config
data:
  .env: |
    # Note: This is a placeholder. In production, use Kubernetes secrets
    # or a secrets management solution for sensitive information
    OPENAI_API_KEY=your-api-key
    DOCKER_HOST=unix:///var/run/docker.sock 