apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-deployment
  labels:
    app: controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: controller
  template:
    metadata:
      labels:
        app: controller
    spec:
      containers:
      - name: controller
        image: browser-controller:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8000
        envFrom:
        - configMapRef:
            name: browser-infra-config
        resources:
          limits:
            cpu: "1"
            memory: "1Gi"
          requests:
            cpu: "500m"
            memory: "512Mi"
      # Using hostAliases to map host.minikube.internal to host machine
      hostAliases:
      - ip: "192.168.49.1"  # Default Minikube gateway IP
        hostnames:
        - "host.minikube.internal"
        - "host.docker.internal"
      volumes:
      - name: config-volume
        configMap:
          name: browser-infra-config 