apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-deployment
  labels:
    app: controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: controller
  template:
    metadata:
      labels:
        app: controller
    spec:
      containers:
      - name: controller
        image: us-central1-docker.pkg.dev/browser-infra/browser-infra/controller:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        envFrom:
        - configMapRef:
            name: browser-infra-config
        resources:
          limits:
            cpu: "1"
            memory: "1Gi"
          requests:
            cpu: "500m"
            memory: "512Mi"
      hostAliases:
      - ip: "host-gateway"
        hostnames:
        - "host.docker.internal"
      volumes:
      - name: config-volume
        configMap:
          name: browser-infra-config 