apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-deployment
  labels:
    app: worker
spec:
  replicas: 2
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
      - name: worker
        image: us-central1-docker.pkg.dev/browser-infra/browser-infra/worker:latest
        imagePullPolicy: Always
        env:
        - name: HEALTH_PORT
          value: "3000"
        envFrom:
        - configMapRef:
            name: browser-infra-config
        ports:
        - containerPort: 3000
        resources:
          limits:
            cpu: "1"
            memory: "2Gi"
          requests:
            cpu: "500m"
            memory: "1Gi"
      hostAliases:
      - ip: "host-gateway"
        hostnames:
        - "host.docker.internal" 