apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
  labels:
    app: worker
spec:
  replicas: 2  # Initial number of worker instances
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
      - name: browser
        image: worker:latest
        imagePullPolicy: IfNotPresent
        command: ["python", "browser_worker.py"]
        ports:
        - containerPort: 3000
        resources:
          limits:
            cpu: "1000m"
            memory: "1Gi"
          requests:
            cpu: "500m"
            memory: "512Mi" 