apiVersion: v1
kind: Service
metadata:
  name: worker
  labels:
    app: worker
spec:
  type: ClusterIP
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
    name: http
  selector:
    app: worker 