apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-deployment
  labels:
    app: worker
spec:
  replicas: 2
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
      - name: worker
        image: browser-worker:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: LIVE_VIEW_PORT
          value: "3000"
        envFrom:
        - configMapRef:
            name: browser-infra-config
        ports:
        - containerPort: 3000
          name: live-view
        resources:
          limits:
            cpu: "1"
            memory: "2Gi"
          requests:
            cpu: "500m"
            memory: "1Gi"
      hostAliases:
      - ip: "192.168.49.1"
        hostnames:
        - "host.minikube.internal"
        - "host.docker.internal" 